### ISSUE TITLE
AutoCorrelation (ACF)

### ISSUE THREAD

**Issue by AntoineGekiere** [BioDataScience-Course/sdd3-19m-ts-AntoineGekiere#1]
Bonjour @GuyliannEngels , 

Je ne parviens pas bien à cerner l'interprétation qui peut être faite à partir d'un graphique d'autocorrelation dans le cadre des séries spatio-temporelles. 
Il me semble que ce graphique nous permette de mettre en évidence des cycles, est-ce le cas ? 
Si l'autocorrelation n'est **jamais significative**, cela signifie donc qu'en fait, nous n'avons pas à faire à une série spatio-temporelle (ex : DataSet fire.txt) ??
Dans le cadre du DataSet "Schizophrénie", le fait de voir une autocorrelation négative après 60 jours signifie que le traitement est bel et bien efficace ? 

Un tout grand merci d'avance !

**Comment by GuyliannEngels** [comment]
Bonjour @AntoineGekiere ,

Une série spatio-temporelle est caractérisée par une autocorrélation non nulle. On comprend effectivement que l'observation au temps t1 sera corrélée à t0 + Delta t. Nos observation ne sont pas indépendantes les unes des autres. 

La graphique obtenu avec l'ACF te permet de mettre en évidence la corrélation entre ta série et ta série décalé. Il est possible d'également mettre en évidence des cycles. durant les prochianes séances, tu vas découvrir des outils bien plus intéressant pour mettre en évidence les cycles. 

Dans le cas des feux de forêt nous n'avons effectivement pas d'autocorrélation. Si il n'y a pas d'autocorrelation, la série suit les mêmes propriétés qu'une série aléatoire. Les feux de forêts sont dus au hazard.

A nouveau, je pense que tu veux aller trop vite. Après 60 jours, la corrélation s'inverse dans le jeu de données sur la schizophrénie. Tu vas découvrir des outils bien plus puissant pour mettre en évidence les différences avant et après la prise du médicament. 

Bonne journée

**Comment by GuyliannEngels** [comment]
A la suite d'une discussion avec @phgrosjean , je vais corriger une imprécision dans mon message précédent. 

Les séries spatio-temporelles, comme leur nom l'indique, sont constituées d'une succession d'observation d'une ou plusieurs variables dans le temps (ou dans l'espace) mesurées sur le(s) même(s) individu(s). 

Une série spatio-temporelles peut donc ne pas être autocorrélée.
