### ISSUE TITLE
Informations cernes.txt

### ISSUE THREAD

**Issue by AntoineGekiere** [BioDataScience-Course/sdd3-19m-ts-AntoineGekiere#2]
Bonjour @GuyliannEngels ,
Est-ce que vous pourriez nous confier des informations supplémentaires concernant le jeu de données cernes.txt (croissance d'arbres) car mis-à-part le fait que les mesures soient réalisées à partir de 1973, nous ne savons rien concernant l'information temporelle nécessaire pour paramétrer le jeu de données en série spatio-temporelle via la fonction *ts()* ? 
Un grand merci.

**Comment by GuyliannEngels** [comment]
Salut @AntoineGekiere ,

Ta série se termine en 1973 et une mesure a été réalisée par an. Avec ces informations, tu devrais être capable de paramétrer ta fonction ts()

**Comment by GuyliannEngels** [comment]
- Si j'ai répondu à ta question, ferme cette issue,

- Si tu as encore une question concernant `Informations cernes.txt` , n'hésite pas à la poser dans cette ISSUE
