### ISSUE TITLE
Temperature Melbourne

### ISSUE THREAD

**Issue by AntoineGekiere** [BioDataScience-Course/sdd3-19m-ts-AntoineGekiere#3]
Bonjour @GuyliannEngels ,
Je rencontre un souci dans le cadre de l'étude spatio-temporelle de la température à Melbourne.
Je pense que c'est la première fois qu'on se heurte à un jeu de données organisé de la sorte, à savoir en 3 colonnes : année, mois, température. 
Pourriez-vous nous éclairer dans le code à utiliser pour transformer en *Time Serie ts()* afin de faire comprendre à la machine une telle organisation du jeu de données ? 
Mille merci !

**Comment by GuyliannEngels** [comment]
Salut @AntoineGekiere ,

Il me semble que tu as toutes les informations afin de remplir les aguments de ta fonction ts().
tu peux facilement sélectionner une variable d'intérêt avec l'opérateur `$` et puis employer les mois et les années comme indications pour compléter les arguments de la fonction ts()

**Comment by AntoineGekiere** [comment]
Merci bien. Je n'avais pas pensé à simplement créer un nouveau jeu de données en gardant uniquement la colonne d'intérêt via la fonction *select()*. 
J'ai également pu l'appliquer pour d'autres jeux de données similaires. 
À demain
