### ISSUE TITLE
Tendance locale (Time Series)

### ISSUE THREAD

**Issue by AntoineGekiere** [BioDataScience-Course/sdd3-19m-ts-AntoineGekiere#4]
Bonjour @GuyliannEngels , Bonjour @phgrosjean ,
Dans le cadre de l'étude de séries temporelles sur des jeux de données comme _Température Melbourne_ ou encore _Milk Product_, j'ai pu remarquer la chose suivante que je ne parviens pas à expliquer. 
Lors d'une analyse de tendance générale via *trend.test()*, ces 2 jeux de données présentent un coefficient de Spearman significativement >0 au seuil $\alpha = 5%$. Il y a donc une tendance globale à l'augmentation. 
Toutefois, lorsqu'une analyse de tendance locale est réalisée sur ces jeux de données via *local.trend()* et qu'un lissage de la courbe est effectué avec *aggregate()*, l'observation suivante peut être faite : un décroissance peut être observée sur la moitié de l'intervalle de temps total, suivi ensuite d'une augmentation. Or, le coefficient de Spearman (ainsi que l'allure nette de la courbe à l'oeil nu) nous montre que la tendance est complètement à la hausse. 
Dès lors, est-ce bien significatif d'interpréter sur le court terme quelque chose comme "On peut observer une réduction de température de 1981 à 1987, suivie d'une réaugmentation" ?
Un grand merci pour votre prise en considération et votre aide.

**Comment by phgrosjean** [comment]
Bonjour @AntoineGekiere,

Je ne vois pas ces analyses de tendances dans ton dépôt. N'aurais-tu pas oublié de faire un dernier commit par hasard? Tes analyses de la température à Melbourne et de la production de lait s'arrêtent à l'ACF (et d'ailleurs, attention, tu parles d'un cycle de 6 mois pour la température à Melbourne, alors que c'est bien évidemment un cycle annuel).

Je pourrai commenter tes analyses lorsque je pourrai les voir. Indiques-moi où je peux les trouver.

**Comment by AntoineGekiere** [comment]
Bonjour @phgrosjean 
Mea culpa ! J'avais en effet oublié de réaliser un dernier **Push**. 
Voilà qui est fait, vous pourrez dès lors trouvez ces analyses dans la section me concernant. 
Un grand merci. 
Bonne après-midi.

**Comment by phgrosjean** [comment]
Ah, je comprend maintenant ce qui te chiffonne en regardant tes commentaires pour la tendance locale pour la production de lait. La tendance locale détermine les périodes de valeurs moyennes supposées constantes. Donc, cette méthode fonctionne quand on peut considérer des périodes avec des valeurs moyennes stables dans le temps. Pour la production de lait, ce n'est pas le cas: on a un forte tendance générale à l'augmentation (progressive). Donc, les tendances locales ne sont pas utiles ici.

Pour la température à Melbourne, c'est le contraire: comme sur l'ensemble de la série, on a deux périodes avec des valeurs moyennes différentes, une tendance générale ne peut pas être détectée, mais la méthode des tendances locales permet de discerner ces deux périodes... Et non, cette méthode ne détermine pas si les températures sont en augmentation ou en diminution durant chaque période, mais seulement que les valeurs moyennes diffèrent entre elles!

**Comment by AntoineGekiere** [comment]
Bonjour Monsieur @phgrosjean ,
Merci pour votre retour. 
Le concept reste légèrement flou à mes yeux. Ainsi, la tendance locale peut un peu être vue comme une statistique glissante sur les moyennes ? L'avantage de cette méthode de somme cumulée serait donc de nous montrer quelles sont les intervalles de temps à considérer ? 
Peut-on dès lors dire que, lorsqu'une tendance générale significative est notée, tout recherche de tendance locale par la méthode des sommes cumulées est inutile ? 
Merci.

**Comment by phgrosjean** [comment]
C'est pas franchement mutuellement exclusif, mais c'est pas loin d'une approche saine: soit l'un, soit l'autre.
