### ISSUE TITLE
Filtrage par Médiane mobile (decmedian)

### ISSUE THREAD

**Issue by AntoineGekiere** [BioDataScience-Course/sdd3-19m-ts-AntoineGekiere#5]
Bonjour @phgrosjean , Bonjour @GuyliannEngels ,
Je me heurte à une incompréhension concernant l'algorithme qui se cache derrière la fonction ***decmedian***. En effet, celle-ci, toute comme *decaverage*, s'intéresse à une fenêtre de k valeurs à gauche et de k valeurs à droite de la valeur qui nous importe. Dans le cas de *decaverage*, chaque observation est remplacée par la valeur de la moyenne de la fenêtre centrée sur cette observation. Mais qu'en est-il de *decmedian* ? Car si cette dernière fonctionne d'après le même raisonnement, chaque valeur serait remplacée par ... elle-même **(!)** puisqu'elle serait la valeur au centre de la fenêtre à chaque fois, et ainsi la médiane de cette fenêtre de valeurs. Dès lors, la série filtrée serait identique à la série initiale, ce qui n'est pas le cas en pratique évidemment. 
Ainsi, je me demandais si, contrairement à *decaverage*, *decmedian* ne remplaçait en fait pas toutes les valeurs t par une valeur $M_{t}$. 
Merci d'avance !

**Comment by phgrosjean** [comment]
Cela ne concerne que les valeurs aux extrémités. Le traitement est le même que pour les moyennes mobiles, mais en remplaçant les moyennes par les médianes.
